version: 1

before:
  hooks:
    - go mod tidy
    - go generate ./...
    - go test ./...

builds:
  - id: loex
    binary: loex
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
    flags:
      - -trimpath

archives:
  - id: loex
    builds:
      - loex
    format: tar.gz
    name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    files:
      - README.md
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^refactor:'
      - '^style:'
      - '^chore:'
      - Merge pull request
      - Merge branch
      - '^Initial commit'
  groups:
    - title: '🚀 New Features'
      regexp: '^.*?feat(\(.+\))??!?:.+$'
      order: 0
    - title: '🐛 Bug Fixes'
      regexp: '^.*?(fix|bug)(\(.+\))??!?:.+$'
      order: 1
    - title: '⚡ Performance Improvements'
      regexp: '^.*?perf(\(.+\))??!?:.+$'
      order: 2
    - title: '🔧 Improvements'
      regexp: '^.*?(improve|enhance|update)(\(.+\))??!?:.+$'
      order: 3
    - title: '📚 Documentation'
      regexp: '^.*?docs(\(.+\))??!?:.+$'
      order: 4
    - title: '🏗️ Build & CI'
      regexp: '^.*?(build|ci)(\(.+\))??!?:.+$'
      order: 5
    - title: '🔄 Other Changes'
      order: 999

brews:
  - name: loex
    description: "Loex: Local Execution Manager CLI"
    homepage: "https://github.com/kjunh972/loex"
    license: "MIT"
    
    repository:
      owner: kjunh972
      name: homebrew-loex
      branch: main
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    
    folder: Formula
    
    # Custom install script
    install: |
      bin.install "loex"
      
      # Install shell completions
      generate_completions_from_executable(bin/"loex", "completion")
    
    # Test script
    test: |
      system "#{bin}/loex", "--version"
      system "#{bin}/loex", "--help"
    
    # Dependencies
    dependencies:
      - name: go
        type: build
    
    # Caveats shown after installation
    caveats: |
      Get started with Loex:
        loex init myproject
        loex config wizard myproject
        loex start myproject
      
      For more information, run: loex --help

release:
  github:
    owner: kjunh972
    name: loex
  
  draft: false
  prerelease: auto
  
  name_template: "{{.ProjectName}} v{{.Version}}"
  
  header: |
    ## 🎉 Loex {{.Version}} Release
    
    Thank you for using Loex! This release includes the following changes:
    
  footer: |
    ## 📦 Installation
    
    ### 🍺 Homebrew (Recommended)
    ```bash
    brew tap kjunh972/loex && brew install loex
    ```
    
    ### 📥 Direct Download
    Download the appropriate binary for your platform from the assets below:
    - **macOS**: `loex-{{.Version}}-darwin-amd64.tar.gz` (Intel) / `loex-{{.Version}}-darwin-arm64.tar.gz` (Apple Silicon)
    - **Linux**: `loex-{{.Version}}-linux-amd64.tar.gz` (x86_64) / `loex-{{.Version}}-linux-arm64.tar.gz` (ARM64)
    
    ### 🚀 Quick Start
    ```bash
    # Initialize a project
    loex init myproject
    
    # Auto-detect services in current directory
    loex detect myproject
    
    # Start all services
    loex start myproject
    ```
    
    ### 📋 What's Next?
    - Check out the [documentation](https://github.com/kjunh972/loex/blob/main/README.md) for more examples
    - Report issues or suggest features on [GitHub Issues](https://github.com/kjunh972/loex/issues)
    
    **Full Changelog**: https://github.com/kjunh972/loex/compare/{{ .PreviousTag }}...{{ .Tag }}
    
    ---
    
    💡 **Pro tip**: Use `loex -v` to check your current version and `loex --help` for all available commands!

announce:
  skip: true